alias: Rega Oliveiras
description: ""
trigger:
  - platform: time
    at: "21:00:00"
  - platform: time
    at: "07:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.rainsensor_3
    state: "off"
  - condition: numeric_state
    entity_id: sensor.oliveira_soil_moisture_2
    below: 40
action:
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.pipe1_3
  - delay:
      hours: 0
      minutes: 0
      seconds: 35
      milliseconds: 0
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.pipe2_3
mode: single